spring:
  profiles:
    active: dev
  application:
    name: ugur
    version: 1.0.0

  webflux:
    multipart:
      max-in-memory-size: 1024

  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false


  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/ugur
    user: postgres
    password: postgres
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/ugur
    username: postgres
    password: postgres
    pool:
      enabled: true
      initial-size: 10
      max-size: 50
      max-idle-time: 30m
      max-acquire-time: 60m
      validation-query: 60m

gps:
  scheduling:
    enabled: true

  tugdk:
    enabled: true

    url: "https://gps.tugdk.gov.tm/api"
    bearer-token: "${TUGDK_GPS_TOKEN:sfdsfsdfsdfsfsfsft4t4t43543543efgdf}"

    timeout: 10s
    max-retries: 3
    retry-delay: 2s

    polling-interval: 30s
    max-data-age: 5m

    caching-enabled: true
    cache-ttl: 30s

    health-monitoring-enabled: true
    health-check-interval: 1m

    circuit-breaker:
      enabled: true
      failure-threshold: 5
      success-threshold: 3
      timeout: 30s
      wait-duration: 1m

    rate-limit:
      enabled: true
      max-requests: 100
      time-window: 1m

    metrics:
      enabled: true
      prefix: "tugdk.gps"
      request-duration-enabled: true
      success-rate-enabled: true
      error-rate-enabled: true
      data-quality-enabled: true

    polling:
      enabled: true

  ayauk:
    enabled: true

    url: "https://edu.ayauk.gov.tm/gps"
    username: "${AYAUK_USERNAME:test}"
    password: "${AYAUK_PASSWORD:test}"

    timeout: 15s
    max-retries: 2
    retry-delay: 5s

    polling-interval: 5m
    max-data-age: 1h

    caching-enabled: true
    cache-ttl: 10m

    health-monitoring-enabled: true
    health-check-interval: 5m

    assignment-validation-enabled: true
    conflict-detection-enabled: true
    auto-refresh-enabled: true

    metrics:
      enabled: true
      prefix: "ayauk.routes"
      request-duration-enabled: true
      assignment-count-enabled: true
      route-coverage-enabled: true
      conflict-detection-enabled: true

    assignment-validation:
      date-validation-enabled: true
      vehicle-id-validation-enabled: true
      route-number-validation-enabled: true
      max-assignment-age-days: 7
      duplicate-detection-enabled: true


logging:
  level:
    tm.ugur.ugur_v3.infrastructure.external.gps: DEBUG
    reactor.netty.http.client: INFO
    org.springframework.web.reactive.function.client: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true






